import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { CommentThread } from "./CommentThread";
import { FavoriteButton } from "./FavoriteButton";
import { ReactionBar } from "./ReactionBar";
import { StoryTimeline } from "./StoryTimeline";
import { SlugRule } from "./press";
import { timeAgo } from "../lib/time";
import type { StoryDetail } from "../types";

/** "45m", "18h", "2d" -- the same compact span the feed prints. */
function formatSpan(hours: number): string {
  if (hours < 1) return `${Math.round(hours * 60)}m`;
  if (hours < 48) return `${Math.round(hours)}h`;
  return `${Math.round(hours / 24)}d`;
}

/**
 * One story, as a take with its coverage plotted underneath.
 *
 * Two measures on purpose. The prose runs in a reading column, because a
 * generated overview set across 1180px is unreadable; the timeline runs the
 * full width, because it is a chart of thirty days and a 20rem sidebar could
 * never be a time axis. A body column with a chart across the page is what a
 * newspaper does with exactly this pair.
 */
export function StoryPage() {
  const { storyId } = useParams();
  const [story, setStory] = useState<StoryDetail | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Reset on id change so story -> story navigation shows the loading
    // state rather than the previous story's content.
    setStory(null);
    setError(null);

    fetch(`/api/stories/${storyId}`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then(setStory)
      .catch((e: Error) => setError(e.message));
  }, [storyId]);

  const back = (
    <Link
      to="/stories"
      className="t-wire inline-block pt-8 text-ink-mute hover:text-ink focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-spot"
    >
      ← All stories
    </Link>
  );

  if (error) {
    return (
      <div>
        {back}
        <h1 className="t-display max-w-[20ch] pt-8 text-[clamp(1.75rem,4vw,2.75rem)] leading-[1.02]">
          No such story.
        </h1>
        <p className="t-read max-w-[46ch] pt-4 text-ink-mute">{error}</p>
      </div>
    );
  }

  if (!story) {
    return (
      <div>
        {back}
        <p className="t-wire pt-8 text-ink-mute">Loading…</p>
      </div>
    );
  }

  const headline = story.summary_title ?? story.title;
  const slug = [
    ...story.teams.map((t) => t.code),
    ...story.categories.map((c) => c.label),
  ].join(" · ");

  return (
    <div>
      {back}

      <article className="pt-8">
        {/* The slug line sits above the headline, the way it does on the
            front page: what this is about before what happened. */}
        <p className="t-wire flex flex-wrap items-center gap-x-2 gap-y-1 text-ink-mute">
          {slug && (
            <>
              <span>{slug}</span>
              <span aria-hidden="true">·</span>
            </>
          )}
          <span className="text-ink">{story.outlet_count} outlets</span>
          <span aria-hidden="true">·</span>
          <span>{story.article_count} articles</span>
          <span aria-hidden="true">·</span>
          <span>{formatSpan(story.span_hours)} span</span>
          <span aria-hidden="true">·</span>
          <span>latest {timeAgo(story.last_at)}</span>
        </p>

        <div className="flex items-start gap-5 pt-3">
          <h1 className="t-display max-w-[22ch] flex-1 text-[clamp(2rem,5vw,3.5rem)] leading-[0.98]">
            {headline}
            {story.summary_title && (
              <span
                title="Headline and subhead generated by AI from member articles"
                className="t-wire ml-3 align-middle text-ink-mute"
              >
                AI
              </span>
            )}
          </h1>
          <div className="shrink-0 pt-3 empty:hidden">
            <FavoriteButton storyId={story.id} />
          </div>
        </div>

        {story.summary_subhead && (
          <p className="t-read max-w-[62ch] pt-4 text-[1.1875rem] text-ink-mute">
            {story.summary_subhead}
          </p>
        )}

        <ReactionBar
          storyId={story.id}
          reactions={story.reactions}
          myReaction={story.my_reaction}
        />

        {story.summary_bullets && story.summary_bullets.length > 0 && (
          <section className="max-w-[68ch] pt-12">
            <SlugRule label="Overview" />
            <ul className="pt-4">
              {story.summary_bullets.map((bullet, i) => (
                <li
                  key={i}
                  className="t-read flex gap-4 border-t border-rule py-3 text-ink first:border-t-0 first:pt-0"
                >
                  <span aria-hidden="true" className="t-wire pt-1.5 text-ink-mute">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span className="min-w-0">{bullet}</span>
                </li>
              ))}
            </ul>

            {story.summary_people && story.summary_people.length > 0 && (
              <p className="t-wire pt-4 text-ink-mute">
                People
                <span aria-hidden="true"> · </span>
                {story.summary_people.join(" · ")}
              </p>
            )}
          </section>
        )}

        {/* Generated text is always attributed, in full, in the reader's
            sight -- not folded away behind a tooltip. */}
        {story.summarized_at && (
          <p className="t-read max-w-[68ch] pt-6 text-[0.9375rem] text-ink-mute">
            Overview generated by {story.summary_model} on{" "}
            {new Date(story.summarized_at).toLocaleString()} from the{" "}
            {story.outlet_count} outlets below. Not written or checked by a human.
          </p>
        )}
      </article>

      <section className="pt-12 md:pt-16">
        <SlugRule label="Coverage" count={story.outlet_count} />
        <div className="pt-4">
          <StoryTimeline
            articles={story.articles}
            firstAt={story.first_at}
            lastAt={story.last_at}
          />
        </div>
      </section>

      <div className="max-w-[68ch]">
        <CommentThread storyId={story.id} />
      </div>
    </div>
  );
}
