import { Link } from "react-router-dom";
import { Sparkline } from "./Sparkline";
import type { Story } from "../types";

/** "45m", "18h", "2d" -- compact enough to sit inline next to the outlet count. */
function formatSpan(hours: number): string {
  if (hours < 1) return `${Math.round(hours * 60)}m`;
  if (hours < 48) return `${Math.round(hours)}h`;
  return `${Math.round(hours / 24)}d`;
}

function timeAgo(iso: string): string {
  const minutes = (Date.now() - new Date(iso).getTime()) / 60000;
  if (minutes < 60) return `${Math.max(1, Math.round(minutes))}m ago`;
  if (minutes < 2880) return `${Math.round(minutes / 60)}h ago`;
  return `${Math.round(minutes / 1440)}d ago`;
}

const CHIP_LIMIT = 5;

export function StoryCard({ story }: { story: Story }) {
  const shown = story.outlets.slice(0, CHIP_LIMIT);
  const remaining = story.outlets.length - shown.length;

  return (
    <Link
      to={`/story/${story.id}`}
      className="group flex flex-col gap-3 rounded-lg border border-ink-200 bg-white p-4
                 transition-colors hover:border-ink-500/40
                 dark:border-white/10 dark:bg-white/5"
    >
      {/* The header is the whole thesis: how many outlets, how fast, what shape. */}
      <div className="flex items-center gap-3">
        <span className="text-sm font-semibold tabular-nums text-ink-900 dark:text-white">
          {story.outlet_count}
          <span className="ml-1 font-normal text-ink-500 dark:text-white/50">
            outlet{story.outlet_count === 1 ? "" : "s"}
          </span>
        </span>

        <Sparkline
          buckets={story.buckets}
          className="text-ink-900/70 dark:text-white/60"
        />

        <span className="ml-auto text-xs tabular-nums text-ink-500 dark:text-white/50">
          {formatSpan(story.span_hours)} span
        </span>
      </div>

      {/* Generated headline when we have one; the seed article's otherwise.
          The AI label is non-negotiable: generated text is always marked. */}
      <h2 className="text-[15px] font-medium leading-snug text-ink-900 dark:text-white">
        {story.summary_title ?? story.title}
        {story.summary_title && (
          <span
            className="ml-1.5 rounded bg-ink-50 px-1 py-px align-middle text-[10px]
                       font-normal uppercase tracking-wide text-ink-500
                       dark:bg-white/10 dark:text-white/50"
            title="Headline and subhead generated by AI from member articles"
          >
            AI
          </span>
        )}
      </h2>

      {story.summary_subhead && (
        <p className="-mt-1 text-[13px] leading-snug text-ink-500 dark:text-white/60">
          {story.summary_subhead}
        </p>
      )}

      {/* Who broke it is the differentiator -- competitors show a count and a
          timestamp, not an ordering. */}
      <p className="text-xs text-ink-500 dark:text-white/50">
        <span className="font-medium text-ink-900/80 dark:text-white/80">
          {story.outlets[0]}
        </span>{" "}
        first &middot; latest {timeAgo(story.last_at)}
        {story.article_count !== story.outlet_count && (
          <> &middot; {story.article_count} articles</>
        )}
      </p>

      <div className="mt-auto flex flex-wrap gap-1 pt-1">
        {shown.map((outlet) => (
          <span
            key={outlet}
            className="rounded bg-ink-50 px-1.5 py-0.5 text-[11px] text-ink-500
                       dark:bg-white/10 dark:text-white/60"
          >
            {outlet}
          </span>
        ))}
        {remaining > 0 && (
          <span className="px-1.5 py-0.5 text-[11px] text-ink-500 dark:text-white/40">
            +{remaining}
          </span>
        )}
      </div>
    </Link>
  );
}
